### ISSUE TITLE
Right click file in explorer, properties -> nothing

### ISSUE THREAD

**Issue by lundman** [lundman/ZFSin#2]
Nothing happens when properties is selected, many queries are issued though

```
  fsDispatcher: enter: major 14: minor 0: IRP_MJ_DEVICE_CONTROL fsDeviceObject
IOCTL_MOUNTDEV_QUERY_DEVICE_NAME
replying with '\'
dispatcher: exit: 0x80000005 Overflow Information 0x4
dispatcher: enter: major 14: minor 0: IRP_MJ_DEVICE_CONTROL
  fsDispatcher: enter: major 14: minor 0: IRP_MJ_DEVICE_CONTROL fsDeviceObject
IOCTL_MOUNTDEV_QUERY_DEVICE_NAME
replying with '\Device\ZFS{0b1bb601-af0b-32e8-a1d2-54c167af6277}'
dispatcher: exit: 0x0 OK Information 0x66
dispatcher: enter: major 2: minor 0: IRP_MJ_CLOSE
  fsDispatcher: enter: major 2: minor 0: IRP_MJ_CLOSE fsDeviceObject
dispatcher: exit: 0x0 OK Information 0x0
dispatcher: enter: major 0: minor 0: IRP_MJ_CREATE
  fsDispatcher: enter: major 0: minor 0: IRP_MJ_CREATE fsDeviceObject
IRP_MJ_CREATE: FileObject FFFFC68633F76320 related 0000000000000000 name '\Pippin3.jpg\' flags 0x0
zfs_vnop_lookup: enter
+zget 4
+zget 9
dispatcher: exit: 0x0 OK Information 0x1
dispatcher: enter: major 13: minor 0: IRP_MJ_FILE_SYSTEM_CONTROL(IRP_MN_USER_FS_REQUEST)
  fsDispatcher: enter: major 13: minor 0: IRP_MJ_FILE_SYSTEM_CONTROL(IRP_MN_USER_FS_REQUEST) fsDeviceObject
    FSCTL_GET_REPARSE_POINT
dispatcher: exit: 0xc0000275 <*****> Information 0x0
dispatcher: enter: major 18: minor 0: IRP_MJ_CLEANUP
  fsDispatcher: enter: major 18: minor 0: IRP_MJ_CLEANUP fsDeviceObject
IRP_MJ_CLEANUP: iocount 0 usecount 2
dispatcher: exit: 0x0 OK Information 0x0
dispatcher: enter: major 2: minor 0: IRP_MJ_CLOSE
  fsDispatcher: enter: major 2: minor 0: IRP_MJ_CLOSE fsDeviceObject
IRP_MJ_CLOSE: iocount 0 usecount 1
dispatcher: exit: 0x0 OK Information 0x0
dispatcher: enter: major 0: minor 0: IRP_MJ_CREATE
  fsDispatcher: enter: major 0: minor 0: IRP_MJ_CREATE fsDeviceObject
IRP_MJ_CREATE: FileObject FFFFC68633F76320 related 0000000000000000 name '\Pippin3.jpg' flags 0x0
zfs_vnop_lookup: enter
+zget 4
+zget 9
dispatcher: exit: 0x0 OK Information 0x1
dispatcher: enter: major 5: minor 0: IRP_MJ_QUERY_INFORMATION
  fsDispatcher: enter: major 5: minor 0: IRP_MJ_QUERY_INFORMATION fsDeviceObject
* query_information: FileStreamInformation
file_stream_information: 
dispatcher: exit: 0x0 OK Information 0xffffc6a6
```
